//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inzynierka_ostatnia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class W33MNAll
    {
        public string UID { get; set; }
        public string POCHODZENIE { get; set; }
        public Nullable<int> NUMER1 { get; set; }
        public Nullable<int> NUMER2 { get; set; }
        public Nullable<System.DateTime> DATALEGU { get; set; }
        public string ROD { get; set; }
        public string LEG { get; set; }
        public Nullable<int> PLEC { get; set; }
        public Nullable<long> MATKA { get; set; }
        public Nullable<long> OJCIEC { get; set; }
        public Nullable<int> MASA8T { get; set; }
        public Nullable<int> MASA11T { get; set; }
        public Nullable<double> PMASY { get; set; }
        public Nullable<double> PPMASY { get; set; }
        public Nullable<int> WPW { get; set; }
        public Nullable<int> MASA1 { get; set; }
        public Nullable<int> SUMAZNJAJ { get; set; }
        public Nullable<int> LJNAL { get; set; }
        public Nullable<int> LJZAP { get; set; }
        public Nullable<int> LPISW { get; set; }
        public Nullable<int> LJAJZW { get; set; }
        public Nullable<int> MASAJAJ { get; set; }
        public Nullable<System.DateTime> DATZNOJ { get; set; }
        public string WADYJAJ { get; set; }
        public Nullable<int> DLMOS { get; set; }
        public Nullable<int> DLPR { get; set; }
        public Nullable<int> GRMP { get; set; }
        public Nullable<double> OMM { get; set; }
        public Nullable<double> POMM { get; set; }
        public Nullable<double> OMT { get; set; }
        public Nullable<double> POMT { get; set; }
        public Nullable<System.DateTime> DATZNPJ { get; set; }
        public string ZDROWIE { get; set; }
        public string WADY { get; set; }
        public Nullable<System.DateTime> DATUB { get; set; }
        public string UWAGI { get; set; }
        public Nullable<bool> USUN { get; set; }
    }
}
